### PR TITLE
JdbcRegisteredClientRepository hashes client secret on save

### PR DESCRIPTION
**Pull request by ovidiupopa91**
Closes gh-378

### CODE REVIEW

**Comment by ovidiupopa91** [comment]
still in draft as I will rebase it on `main` after the changes done in gh-356 are merged.

**Comment by jgrandja** [comment]
Thanks for the PR @ovidiupopa91 ! This is now in main.

**Comment by jgrandja** [comment]
@ovidiupopa91 I think there may be a double-encoding bug with this update. I decided to merge anyway but can you confirm if there is a bug or not.

In the scenario where an existing client is updated via `save()`, the `client-secret` might be double encoded depending on how the backing `PasswordEncoder` is implemented. This would result in a failed client authentication on a subsequent grant flow. Can you please confirm if this is an issue?

FYI, I'm on PTO all of next week and returning Aug 9 so I'll follow up with you then.

Thanks again for all your help !

**Comment by ovidiupopa91** [comment]
Hi @jgrandja . I was thinking about this as well. I will let you know when I have a definitive answer.
Enhoy your time off 😀

**Comment by jgrandja** [comment]
Thanks for confirming @ovidiupopa91.

Would you mind creating a new issue for this with the details?

We'll need to have this fixed before we implement gh-355.

**Comment by ovidiupopa91** [comment]
welcome back @jgrandja . Issue created: gh-389

**Comment by jgrandja** [comment]
Thanks @ovidiupopa91 ! I assigned it to you but this can wait until `0.2.1`.

**Pull request closed without merging**
