### PR TITLE
Add client secret POST authentication method support

### PR DESCRIPTION
**Pull request by anoopgarlapati**
Added support for client secret POST authentication method.
Added validation of client authentication method when
authenticating a client.

Closes gh-134

### CODE REVIEW

**Comment by anoopgarlapati** [comment]
@jgrandja This is ready for your review.
I have verified following the steps mentioned in gh-132 for the sample, I can now obtain access token successfully using this client authentication method.

**Review by jgrandja — CHANGES_REQUESTED** [review]
Thanks for the PR @anoopgarlapati. I left a couple of minor comments.

Also, I'm going to move this to the `0.1.0` release as the changes to the constructor in `OAuth2ClientAuthenticationToken` is a breaking change for a patch release. The `0.1.0` release allows major changes. Also, I'm pretty sure there will be more major API changes when you start working on `Jwt` auth.

**Comment by anoopgarlapati** [comment]
@jgrandja I have rebased this branch against master and resolved the merge conflicts.

**Comment by jgrandja** [comment]
Thanks for all the updates @anoopgarlapati. This is now in master!
FYI, I added a polish commit with very minor updates.

**Pull request merged**
