### PR TITLE
Rename and move SpringSecurityCoreVersion2 to Version

### PR DESCRIPTION
**Pull request by WalidEll**
I've renamed and moved org.springframework.security.oauth2.server.authorization.SpringSecurityCoreVersion2.java to org.springframework.security.oauth2.server.authorization.Version.java

Closes gh-116

### CODE REVIEW

**Comment by jgrandja** [comment]
Thanks for the PR @WalidEll !

This is scheduled for the `0.1.0` release, which will come after the `0.0.2` and `0.0.3` releases.

I'll merge this after we release `0.0.3`, which will be approx. 1-2 months from now.

**Comment by jgrandja** [comment]
@WalidEll I decided to move this to the `0.0.2` release, given that `Version` is an internal class and should be safe to merge. This is now in master.

**Comment by WalidEll** [comment]
let rocket it to the 1.0.0 💯

**Comment by jgrandja** [comment]
For sure!

**Pull request closed without merging**
