### PR TITLE
Add update support in JdbcRegisteredClientRepository

### PR DESCRIPTION
**Pull request by ovidiupopa91**
Closes gh-356

### CODE REVIEW

**Comment by ovidiupopa91** [comment]
let me know if any of the `RegisteredClient` properties should be excluded from the update sql script.

**Review by jgrandja — CHANGES_REQUESTED** [review]
Thanks for the PR @ovidiupopa91 ! Please see review comments.

**Comment by jgrandja** [comment]
@ovidiupopa91 I just realized that we need to hash `client_secret` on `save()`. You will notice that `OAuth2ClientAuthenticationProvider` uses a `PasswordEncoder` when matching on `client_secret`.

Do you have time / interest in adding `JdbcRegisteredClientRepository.RegisteredClientParametersMapper.setPasswordEncoder()` in a separate PR ?

**Comment by ovidiupopa91** [comment]
> @ovidiupopa91 I just realized that we need to hash `client_secret` on `save()`. You will notice that `OAuth2ClientAuthenticationProvider` uses a `PasswordEncoder` when matching on `client_secret`.
> 
> Do you have time / interest in adding `JdbcRegisteredClientRepository.RegisteredClientParametersMapper.setPasswordEncoder()` in a separate PR ?

Hi @jgrandja . Sure, I will do it.

**Comment by ovidiupopa91** [comment]
@jgrandja  I've raised gh-378 for the other task.

**Comment by jgrandja** [comment]
Thanks for the updates @ovidiupopa91 ! This is now in main.

**Pull request closed without merging**
