### PR TITLE
Added GitHub workflow config for PR builds

### LINKED ISSUE #16: Setup GitHub Actions workflow for PRs
When a PR is submitted, we should test any changes by running the build.
The status of build should appear in the UI for the pull request.

### PR DESCRIPTION
**Pull request by kratostaine**
This is to fix #16 

- Have added workflow config for gradle build on PRs
- Updated the README with the GitHub workflow badge instead of the Travis badge

### CODE REVIEW

**Comment by kratostaine** [comment]
The GitHub action [run](https://github.com/spring-projects-experimental/spring-authorization-server/actions/runs/83698599) for this PR, indicating the builds.

**Comment by kratostaine** [comment]
@eleftherias right now the workflow runs on ubuntu, macos and linux runners for Java 8 through 14, and I haven't changed that bit for the PR builds. Do we need it to run that way or should this be modified?

**Comment by kratostaine** [comment]
> I think it would be best if we had a separate workflow for running the build on a pull request.

@eleftherias Yeah I thought of doing the same, but the result of that would be duplicated build configs for push and pull_request events, and whenever we make changes to the build/sonar jobs for push event, we might have to ensure that the same is also added to the pull_request workflow, or else there might be inconsistency across both. Please let me know if we're okay with that?

> My thought is that the PR workflow would also run on ubuntu, macos and linux runners for Java 8 through 14, unless you have an alternative suggestion.

I'm good with that, just wanted to confirm :)

**Comment by eleftherias** [comment]
> the result of that would be duplicated build configs for push and pull_request events, and whenever we make changes to the build/sonar jobs for push event, we might have to ensure that the same is also added to the pull_request workflow, or else there might be inconsistency across both. Please let me know if we're okay with that?
@kratostaine Yes, we are okay with that. 
If a job becomes complex, we can extract it into a script and potentially share the scripts between both workflows, but for now let's keep them isolated.

**Comment by kratostaine** [comment]
The new separate build action run for this PR is [here](https://github.com/spring-projects-experimental/spring-authorization-server/actions/runs/85561195)

**Comment by eleftherias** [comment]
@kratostaine This look ready to merge.
I saw you had it marked as a draft PR. Is there anything else you want to add before we merge?

**Comment by kratostaine** [comment]
> @kratostaine This look ready to merge.
> I saw you had it marked as a draft PR. Is there anything else you want to add before we merge?

Ah, sorry I had missed to mark it ready for review. Thanks for the heads up. I am done with the changes.

**Comment by eleftherias** [comment]
@kratostaine I noticed that this is split up into 3 commits. Could you squash them into one commit and make sure that you have added `Closes gh-16` as part of the commit message.

**Comment by kratostaine** [comment]
> We've been following the convention of putting `Closes gh-...` on the line below the commit message, like this:
> 
> ```
> Added workflow config for builds on PR
> 
> Closes gh-16
> ```

@eleftherias Can that please be added to the [contributor guidelines](https://github.com/spring-projects-experimental/spring-authorization-server/blob/master/CONTRIBUTING.adoc) too?

**Comment by jgrandja** [comment]
@kratostaine Sure I'll add that to the contributing guidelines.

**Comment by eleftherias** [comment]
Thank for the PR @kratostaine! This is now merged into master.

**Pull request merged**
