### PR TITLE
Add Resource Owner Password Credentials Grant

### PR DESCRIPTION
**Pull request by luamas**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@luamas Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects-experimental/spring-authorization-server&pullRequestId=115)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects-experimental/spring-authorization-server&pullRequestId=115) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@luamas Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects-experimental/spring-authorization-server&pullRequestId=115)!

**Comment by jgrandja** [comment]
Thanks for the PR @luamas. However, we will not be providing support for the `password` grant as its deprecated in OAuth 2.1. For reference, see [OAuth 2.1](https://oauth.net/2.1/) and [It's Time for OAuth 2.1](https://aaronparecki.com/2019/12/12/21/its-time-for-oauth-2-dot-1).

Going forward, please reach out first before any work is done on a new feature to make sure it will get accepted as I don't want you (or anyone) to spend unnecessary time on it. It's always best to open an issue for a new feature enhancement to discuss it first before any work is started. Thanks for your understanding.

**Comment by luamas** [comment]
@jgrandja Since some legacy projects still use similar solutions, could you open up extension points for plug-in support

**Comment by jgrandja** [comment]
@luamas We definitely plan on providing an extension point for custom grant types. This will be coming soon but we need to stabilize the API's first and then we will start opening things up to allow for greater customization.

**Comment by luamas** [comment]
Thank you. I hope to see a stable version soon

**Comment by lucianogreiner** [comment]
OAuth 2.1 is still in draft. Are you guys trying to make a future-proof solution here?

**Pull request closed without merging**
